name: proof-of-creation-mintall

services:
  app:
    image: proof-of-creation-mintall
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proof-of-creation-mintall
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - ENV_FROM=system
    env_file:
      - .env
      # - DATABASE_HOST=postgres
      # - DATABASE_PORT=5432
      # - DATABASE_USER=app
      # - DATABASE_NAME=mintall
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      # - AWS_REGION=ap-southeast-1
      # - AWS_SECRET_NAME=prod/mintall-nft-cert-api/private-key
    # depends_on:
    #   - db
    #   - redis

  # db:
  #   image: postgres:latest
  #   container_name: mintall-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mintall
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  # redis:
  #   image: redis:7
  #   container_name: mintall-redis
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis_data:/data
# volumes:
#   postgres_data:
#   redis_data:
