name: proof-of-creation-mintall

services:
  app:
    image: proof-of-creation-mintall
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: proof-of-creation-mintall
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - ENV_FROM=system
    env_file:
      - ../config/.env
    networks:
      - app-network

  # db:
  #   image: postgres:latest
  #   container_name: mintall-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mintall
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  # redis:
  #   image: redis:7
  #   container_name: mintall-redis
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis_data:/data

# volumes:
#   postgres_data:
#   redis_data:

networks:
  app-network:
    external: true
